#!/bin/bash

NBARGS=6
function print_usage() {
    echo
    echo "Usage: $0 <eclipse_directory> <projects_dir> <project> <top_network> <input_sequence> [<reference_file>]"
    echo "    <eclipse_dir>           		Path to the directory where Eclipse is installed"
    echo "    <projects_dir>                Path to the directory containing CAL projects"
    echo "    <project>                     Name of RVC-CAL project containing application to build"
    echo "    <top_network>                 Qualified name of the top network to build"
    echo "    <fifo_size>                 	Fifo size"
    echo "    <input_sequence>              Input file to pass to application"
    echo "    <reference_file>              [Optional] Reference file to use for errors checking"
}

if [ $# -lt $NBARGS ]; then
    print_usage
    exit $E_BADARGS
fi

[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
[ ! -d "$2" ] && echo "Missing CAL projects directory" && print_usage && exit $E_BADARGS
[ -z "$3" ] && echo "Missing project name" && print_usage && exit $E_BADARGS
[ -z "$4" ] && echo "Missing top network qualified name" && print_usage && exit $E_BADARGS
[ -z "$5" ] && echo "Missing fifo size" && print_usage && exit $E_BADARGS
[ ! -s "$6" ] && echo "Missing input sequence" && print_usage && exit $E_BADARGS
[ -f "$7" ] && REFOPTION="-r $7"

ECLIPSE_DIR=$1
PROJECTS_DIR=$2
PROJECT_NAME=$3
NETWORK=$4
FIFO_SIZE=$5
INPUT=$6

SETFIFO="-s $FIFO_SIZE" 
echo "Fifo size set to $FIFO_SIZE"

echo "***START*** $0 $(date -R)"

RUNWORKSPACE=$PROJECTS_DIR
rm -fr $RUNWORKSPACE/.metadata $RUNWORKSPACE/.JETEmitters
rm -fr $RUNWORKSPACE/**/bin

echo "Register Orcc projects in eclipse workspace"
$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                        -application net.sf.orcc.cal.workspaceSetup \
                        -data $RUNWORKSPACE \
                        $PROJECTS_DIR

echo "Generate Orcc IR for $PROJECT_NAME and projects it depends on"
$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                        -application net.sf.orcc.cal.cli \
                        -data $RUNWORKSPACE \
                        $PROJECT_NAME \
                        $NETWORK \
                        -vmargs -Xms40m -Xmx768m

echo "Run simulation"
$ECLIPSE_DIR/eclipse     -nosplash -consoleLog \
                        -application net.sf.orcc.simulators.cli \
                        -data $RUNWORKSPACE \
                        -n \
                        -i $INPUT \
                        -p $PROJECT_NAME \
                        $SETFIFO \
                        $REFOPTION \
                        $NETWORK \
                        -vmargs -Xms40m -Xmx1024m

echo "***END*** $0 $(date -R)"
