#!/bin/bash
## Build the eclipse enviroment by command line

NBARGS=2
function print_usage() {
    echo
    echo "Usage: $0 <eclipse_directory> <repository_url>"
    echo "    <eclipse_directory>           Path to the directory where Eclipse will be installed"
    echo "    <repository_url>              Repository URL (e.g. http://orcc.sourceforge.net/eclipse/ or file:/user/local/path)"
}

if [ $# -lt $NBARGS ]; then
    print_usage
    exit $E_BADARGS
fi

# The eclipse directory (e.g. /opt/eclipse )
ECLIPSE_DIR=$1
# The orcc eclipse plugins respository site (e.g. file:/home/user/orcc/eclipse/plugins/net.sf.orcc.site/target/repository/)
ORCC_REPO=$2

# The Eclipse download url (if you want to change the mirror just select one from https://eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/R/eclipse-rcp-neon-R-linux-gtk-x86_64.tar.gz&format=xml )
ECLIPSE_DOWNLOAD_URL="http://mirror.switch.ch/eclipse/technology/epp/downloads/release/mars/R/eclipse-rcp-mars-R-linux-gtk-x86_64.tar.gz"
ORCC_FEATURES="net.sf.orcc.feature.feature.group"

echo "***START*** $0 $(date -R)"

if [ -d "$ECLIPSE_DIR" ]; then
  echo "Cleaning the eclipse directory"
  rm -rf $ECLIPSE_DIR
fi

echo "Creating an empty eclipse directory"
mkdir $ECLIPSE_DIR

echo "Downloading Eclipse"
wget --progress=dot:mega $ECLIPSE_DOWNLOAD_URL

ECLIPSEARCHIVE=$(echo eclipse-rcp-*.tar.gz)

echo "Uncompressing Eclipse archive"
tar -xzaf $ECLIPSEARCHIVE
# copy it in the right directory
cp -r eclipse/* $ECLIPSE_DIR

echo "Deleting downloaded archives"
rm -rf eclipse
rm $ECLIPSEARCHIVE

echo "Downloading and installing the orcc plugin"
$ECLIPSE_DIR/eclipse   -nosplash -consoleLog \
                        -application org.eclipse.equinox.p2.director \
                        -repository $ORCC_REPO \
                        -followReferences \
                        -installIU $ORCC_FEATURES
rc=$?
if [[ $rc -ne 0 ]] ; then
  echo 'Eclipse setup with orcc plugin failed'; exit $rc
else
  echo 'Eclipse successfully setup with orcc plugin';
fi

echo "***END*** $0 $(date -R)"
