#!/bin/bash

NBARGS=2
function print_usage() {
    echo
    echo "Usage: $0 <eclipse_directory> <plugins_dir>"
    echo "    <eclipse_directory>           Path to the directory where Eclipse is installed"
    echo "    <orcc_dir>                 	Path to the directory where orcc is cloned"
}

if [ $# -lt $NBARGS ]; then
    print_usage
    exit $E_BADARGS
fi

[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
[ ! -d "$2" ] && echo "Missing orcc directory" && print_usage && exit $E_BADARGS

ECLIPSE_DIR=$(readlink -f $1)
ORCC_DIR=$(readlink -f $2)
PLUGINS_DIR=$ORCC_DIR/eclipse/plugins/
JARPLUGINS_DIR=$ORCC_DIR/eclipse/plugins/net.sf.orcc.site/target/repository

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JGRAPHT_DIR=$SCRIPT_DIR/../lib/jgrapht-0.9.0

mkdir -p junit-results
resultsDir=$(readlink -f junit-results)

buildFile=$(mktemp)
cat > $buildFile <<EOF
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project default="unit-tests">
	<target name="unit-tests">
		<junit haltonfailure="no" printsummary="yes" showoutput="true">
			<formatter type="xml" />
			<classpath>
				<pathelement path="\${java.class.path}/"/>
				<fileset dir="${ECLIPSE_DIR}/plugins">
					<include name="org.junit_4*/junit.jar" />
					<include name="*.jar" />
				</fileset>
				<fileset dir="${JARPLUGINS_DIR}">
					<include name="*.jar" />
				</fileset>
				<fileset dir="${JGRAPHT_DIR}">
					<include name="*.jar" />
				</fileset>
			</classpath>
			<batchtest fork="true" todir="${resultsDir}">
				<fileset dir="$PLUGINS_DIR/net.sf.orcc.cal.tests/src">
					<include name="net/sf/orcc/tests/main/*.java" />
				</fileset>
				<fileset dir="$PLUGINS_DIR/net.sf.orcc.cal.tests/xtend-gen">
					<include name="net/sf/orcc/tests/main/*.java" />
				</fileset>
			</batchtest>
		</junit>
	</target>
</project>
EOF

ant -f $buildFile
