#!/bin/bash
## Compile with a orcc backend

NBARGS=6
function print_usage() {
    echo
    echo "Usage: $0 <eclipse_dir> <projects_dir> <backend> <project> <top_network> <output_dir> [<args> <eclipse_ws>]"
    echo "    <eclipse_dir>           		Path to the directory where Eclipse is installed"
    echo "    <projects_dir>                Path to the directory containing CAL projects"
    echo "    <backend>                     Identifier of the backend to use (c, llvm, jade, tta, etc.)"
    echo "    <project>                     Name of RVC-CAL project containing application to build"
    echo "    <top_network>                 Qualified name of the top network to build"
    echo "    <output_dir>                  Path to the directory where output will be generated"
    echo "    <args>                     	[Optional] Arguments/flags needed by backend execution command line"
    echo "    <eclipse_ws>           		[Optional] Path to the directory where Eclipse workspace should be setup"
}

if [ $# -lt $NBARGS ]; then
    print_usage
    exit $E_BADARGS
fi

[ ! -d "$1" ] && echo "Missing eclipse directory" && print_usage && exit $E_BADARGS
[ ! -d "$2" ] && echo "Missing CAL projects directory" && print_usage && exit $E_BADARGS
[ -z "$3" ] && echo "Missing backend name" && print_usage && exit $E_BADARGS
[ -z "$4" ] && echo "Missing project name" && print_usage && exit $E_BADARGS
[ -z "$5" ] && echo "Missing top network qualified name" && print_usage && exit $E_BADARGS
[ -z "$6" ] && echo "Missing output directory" && print_usage && exit $E_BADARGS

ECLIPSE_DIR=$1
PROJECTS_DIR=$2
BACKEND=$3
PROJECT_NAME=$4
NETWORK=$5
OUTPUT_DIR=$6
ARGS=$7
ECLIPSE_WS=${8:-"eclipse_workspace"}

echo "***START*** $0 $(date -R)"

[ ! -d "$OUTPUT_DIR" ] && mkdir -p $OUTPUT_DIR
[ ! -d "$ECLIPSE_WS" ] && mkdir -p $ECLIPSE_WS

RUNWORKSPACE=$ECLIPSE_WS

rm -fr $RUNWORKSPACE/.metadata $RUNWORKSPACE/.JETEmitters
rm -fr $RUNWORKSPACE/**/bin

echo "Register Orcc projects in eclipse workspace"
$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
                        -application net.sf.orcc.cal.workspaceSetup \
                        -data $RUNWORKSPACE \
                        $PROJECTS_DIR

echo "Generate Orcc IR for $PROJECT_NAME and projects it depends on"
$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
                        -application net.sf.orcc.cal.cli \
                        -data $RUNWORKSPACE \
                        $PROJECT_NAME \
                        $NETWORK \
                        -vmargs -Xms40m -Xmx768m

rm -fr $OUTPUT_DIR/*

echo "Build application with $BACKEND backend"
$ECLIPSE_DIR/eclipse    -nosplash -consoleLog \
                        -application net.sf.orcc.backends.$BACKEND \
                        -data $RUNWORKSPACE \
                        -p $PROJECT_NAME \
                        -o $OUTPUT_DIR \
                        $ARGS \
                        $NETWORK \
                        -vmargs -Xms40m -Xmx768m

rc=$?
if [[ $rc -ne 0 ]] ; then
  echo '$NETWORK compilation with $BACKEND backend failed'; exit $rc
else
  echo '$NETWORK successfully compiled with $BACKEND backend';
fi

echo "***END*** $0 $(date -R)"
