#!/bin/bash

NBARGS=1
function print_usage() {
    echo
    echo "Usage: $0 <orcc_directory> <empty_maven_repository>"
    echo "    <orcc_directory>     Path to the directory where orcc is cloned"
    echo "    <maven_repository>  (optional) the local maven repository path (current data will be erased)"
}

if [ $# -lt $NBARGS ]; then
    print_usage
    exit $E_BADARGS
fi

[ ! -d "$1" ] && echo "Missing orcc directory" && print_usage && exit $E_BADARGS
[ ! "$(ls -A $1)" ] && echo "Empty orcc directory" && print_usage && exit $E_BADARGS

ORCC_DIR=$1
CURR_DIR=${pwd}
MAVEN=$2

echo "***START*** $(date -R)"

if [ -n "$MAVEN" ]; then
	if [ ! -d "$MAVEN" ]; then
		mkdir -p $MAVEN
	else
		rm -fR $MAVEN/*
	fi
fi

cd $ORCC_DIR/eclipse/plugins/
if [ -z "$MAVEN" ]; then
	mvn install 
else
	mvn install -Dmaven.repo.local=$MAVEN
fi

rm -fR $MAVEN

rc=$?
cd $CURR_DIR

if [[ $rc -ne 0 ]] ; then
  echo 'Orcc build failed'; exit $rc
else
  echo 'Orcc plugin successfully built.';
  echo "Orcc plugin site URI: file:$ORCC_DIR/eclipse/plugins/net.sf.orcc.site/target/repository/"
fi

echo "***END*** $0 $(date -R)"
